[package]
name = "nes-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
bitflags = "2.0.0-rc.1"
clap = { version = "4.0.29", features = ["derive"] }
